# Generated by Django 6.0.3 on 2026-05-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='age',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='country',
        ),
        migrations.AddField(
            model_name='myuser',
            name='entidad',
            field=models.CharField(default='CIUDAD DE MEXICO', max_length=128),
        ),
        migrations.AddField(
            model_name='myuser',
            name='genero',
            field=models.CharField(choices=[('MUJER', 'Mujer'), ('HOMBRE', 'Hombre'), ('OTRO', 'Otro')], default='MUJER', max_length=10),
        ),
    ]
