# Generated by Django 6.0.5 on 2026-05-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0002_rename_age_myuser_edad_rename_name_myuser_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Flux',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
