# Generated by Django 6.0.5 on 2026-05-28 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0003_visitante_delete_flux_delete_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='nombre',
        ),
        migrations.AddField(
            model_name='visitante',
            name='edad',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='visitante',
            name='estado',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitante',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=datetime.time(20, 10, 46, 149878)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitante',
            name='sexo',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitante',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
